[pytest]
addopts = --import-mode=importlib --ignore=tests/e2e
testpaths = tests router/tests litellm/tests
norecursedirs = clickhouse-data postgres-data langfuse-data redis-lf-data valkey-data minio-data .git .github scripts
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning
    ignore::starlette.exceptions.StarletteDeprecationWarning
