FROM docker.io/library/python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn httpx pyyaml

COPY main.py /app/main.py

EXPOSE 5000

ENV CONFIG_PATH=/config/config.yaml

CMD ["python", "main.py"]
